---
title: 异常处理
---
## Go语言的异常处理

### 异常处理

​	Go语言并没有其他语言的try except这类异常处理机制，但是Go语言的多返回值的特性可以巧妙且优雅的解决这个问题

异常处理最佳实践：

​	1.单独声明异常，方便判断异常类型

​	2.尽早结束，减少嵌套

```go
package main

import (
   "errors"
   "fmt"
)
var less = errors.New("less than 2")
var more = errors.New("more than 100")
func fib(n int) ([]int,error){
   if n <2 {
      return nil,less
   }
   if n>100{
      return nil,more
   }
   fibList := []int{1,1}
   for i:=2;i<n;i++{
      fibList = append(fibList, fibList[i-1]+fibList[i-2])
   }
   return fibList,nil
}

func main(){
   if v,err := fib(10);err!=nil{
      if err == less{
         fmt.Println("less")
      }
      if err == more{
         fmt.Println("more")
      }
   }else{
      fmt.Println(v)
   }

   if v,err := fib(-10);err!=nil{
      fmt.Println(err)
   }else{
      fmt.Println(v)
   }
}
```

### panic 和recover

panic

​	退出会执行defer函数，并打出当前调用栈信息

os.Exit

​	os.Exit 退出时不会调用defer指定的函数，不输出当前调用栈信息

panic&recover使用

```
package main

import (
	"errors"
	"fmt"
)

func main(){
	defer func() {
		if err := recover();err!=nil{	//recover可以捕获panic的异常，可以进行修复，避免程序退出
			fmt.Println(err)
		}
	}()
	fmt.Println("start")
	panic(errors.New("it is panic"))	//panic 参数是一个error ，会触发defer
}

```

注意，有时候并不是捕获异常避免退出就是合理的解决方式，反倒有可能会让默写异常无法恢复导致服务不可用